name: skyxplorer
description: See daily pictures from NASA.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio_http_formatter: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
